// Version constants and handshake helpers

// Mechanism schema types
export * from './generated/mechanism/mechanism_pb.js';
// Selected generated types for consumers
export type {
  AnalyzeFacePairCommand,
  AnalyzeFacePairResult,
  AnalyzeFacePairSuccess,
  AttachGeometryCommand,
  AttachGeometryResult,
  BodyImportResult,
  CreatePrimitiveBodyCommand,
  CreatePrimitiveBodyResult,
  CompilationResultEvent,
  CompileMechanismCommand,
  CreateActuatorCommand,
  CreateActuatorResult,
  CreateBodyCommand,
  CreateBodyResult,
  CreateDatumCommand,
  CreateDatumFromFaceCommand,
  CreateDatumFromFaceResult,
  CreateDatumFromFaceSuccess,
  CreateDatumResult,
  CreateJointCommand,
  CreateJointResult,
  CreateLoadCommand,
  CreateLoadResult,
  DeleteBodyCommand,
  DeleteBodyResult,
  DeleteDatumCommand,
  DeleteDatumResult,
  DeleteActuatorCommand,
  DeleteActuatorResult,
  DeleteJointCommand,
  DeleteJointResult,
  DeleteLoadCommand,
  DeleteLoadResult,
  DetachGeometryCommand,
  DetachGeometryResult,
  EngineStatus,
  Event,
  GeometryImportResult,
  HandshakeAck,
  ImportAssetCommand,
  ImportAssetResult,
  ImportOptions,
  LoadProjectCommand,
  LoadProjectResult,
  LoadProjectSuccess,
  MissingAssetInfo,
  NewProjectCommand,
  NewProjectResult,
  OutputChannelDescriptor,
  PlaceAssetInSceneCommand,
  PlaceAssetInSceneResult,
  PrepareFacePickingCommand,
  PrepareFacePickingResult,
  PrepareFacePickingSuccess,
  RelocateAssetCommand,
  RelocateAssetResult,
  RenameDatumCommand,
  RenameDatumResult,
  UpdateBodyCommand,
  UpdateBodyResult,
  UpdateDatumPoseCommand,
  UpdateDatumPoseResult,
  UpdateMassPropertiesCommand,
  UpdateMassPropertiesResult,
  SaveProjectCommand,
  SaveProjectResult,
  ScrubCommand,
  SimulationControlCommand,
  SimulationFrame,
  SimulationStateEvent,
  SimulationTrace,
  TimeSample,
  SimulationSettings,
  CompilationDiagnostic,
  SolverSettings,
  ContactSettings,
  CreateSensorCommand,
  CreateSensorResult,
  DeleteSensorCommand,
  DeleteSensorResult,
  UpdateActuatorCommand,
  UpdateActuatorResult,
  UpdateSensorCommand,
  UpdateSensorResult,
  UpdateJointCommand,
  UpdateJointResult,
  UpdateLoadCommand,
  UpdateLoadResult,
  MakeCompoundBodyCommand,
  MakeCompoundBodyResult,
  MakeCompoundBodySuccess,
  SplitBodyCommand,
  SplitBodyResult,
  SplitBodySuccess,
  ReparentGeometryCommand,
  ReparentGeometryResult,
  ReparentGeometrySuccess,
} from './generated/protocol/transport_pb.js';
export {
  ChannelDataType,
  CompilationDiagnosticSchema,
  ContactSettingsSchema,
  DiagnosticSeverity,
  EngineStatus_State,
  FacePairAlignment,
  FaceSurfaceClass,
  ImportMode,
  IntegratorType,
  SimStateEnum,
  SimulationAction,
  SolverSettingsSchema,
  SolverType,
} from './generated/protocol/transport_pb.js';
// Binary transport helpers
export {
  commandToDebugJson,
  createAnalyzeFacePairCommand,
  createAttachGeometryCommand,
  createCreateActuatorCommand,
  createCreateSensorCommand,
  createCreateBodyCommand,
  createCompileMechanismCommand,
  createCreateDatumCommand,
  createCreateDatumFromFaceCommand,
  createCreateJointCommand,
  createCreateLoadCommand,
  createDeleteActuatorCommand,
  createDeleteSensorCommand,
  createDeleteBodyCommand,
  createDeleteDatumCommand,
  createDeleteGeometryCommand,
  createDeleteJointCommand,
  createDeleteLoadCommand,
  createDetachGeometryCommand,
  createHandshakeCommand,
  createCreatePrimitiveBodyCommand,
  createImportAssetCommand,
  createPlaceAssetInSceneCommand,
  createPrepareFacePickingCommand,
  createLoadProjectCommand,
  createNewProjectCommand,
  createPingCommand,
  createRelocateAssetCommand,
  createRenameDatumCommand,
  createRenameGeometryCommand,
  createUpdateDatumPoseCommand,
  createUpdateGeometryPoseCommand,
  createUpdateMassPropertiesCommand,
  createUpdatePrimitiveCommand,
  createUpdateCollisionConfigCommand,
  createSaveProjectCommand,
  createScrubCommand,
  createSimulationControlCommand,
  createUpdateActuatorCommand,
  createUpdateSensorCommand,
  createUpdateBodyCommand,
  createUpdateJointCommand,
  createUpdateLoadCommand,
  createMakeCompoundBodyCommand,
  createSplitBodyCommand,
  createReparentGeometryCommand,
  engineStateToString,
  eventToDebugJson,
  mapFacePairAlignment,
  mapJointType,
  mapMotionType,
  mapSensorAxis,
  mapSensorType,
  parseCommand,
  parseEvent,
  toProtoJointType,
  toProtoMotionType,
  toProtoSensorAxis,
  toProtoSensorType,
  type ImportModeType,
  type MotionTypeId,
  type SensorAxisId,
  type SensorTypeId,
  type CollisionConfigInput,
  type CollisionShapeTypeId,
  type FacePairAlignmentId,
  type PrimitiveParamsInput,
  type PrimitiveShapeType,
  type SimulationSettingsInput,
  type SolverSettingsInput,
  type ContactSettingsInput,
} from './transport.js';
export {
  createHandshake,
  isCompatible,
  PROTOCOL_NAME,
  PROTOCOL_VERSION,
  type ProtocolHandshake,
} from './version.js';
