// Version constants and handshake helpers

// Mechanism schema types
export * from './generated/mechanism/mechanism_pb.js';
// Selected generated types for consumers
export type {
  AttachGeometryCommand,
  AttachGeometryResult,
  BodyImportResult,
  CreatePrimitiveBodyCommand,
  CreatePrimitiveBodyResult,
  CompilationResultEvent,
  CompileMechanismCommand,
  CreateActuatorCommand,
  CreateActuatorResult,
  CreateBodyCommand,
  CreateBodyResult,
  CreateDatumCommand,
  CreateDatumFromFaceCommand,
  CreateDatumFromFaceResult,
  CreateDatumFromFaceSuccess,
  CreateDatumResult,
  CreateJointCommand,
  CreateJointResult,
  CreateLoadCommand,
  CreateLoadResult,
  DeleteBodyCommand,
  DeleteBodyResult,
  DeleteDatumCommand,
  DeleteDatumResult,
  DeleteActuatorCommand,
  DeleteActuatorResult,
  DeleteJointCommand,
  DeleteJointResult,
  DeleteLoadCommand,
  DeleteLoadResult,
  DetachGeometryCommand,
  DetachGeometryResult,
  EngineStatus,
  Event,
  GeometryImportResult,
  HandshakeAck,
  ImportAssetCommand,
  ImportAssetResult,
  ImportOptions,
  LoadProjectCommand,
  LoadProjectResult,
  LoadProjectSuccess,
  MissingAssetInfo,
  NewProjectCommand,
  NewProjectResult,
  OutputChannelDescriptor,
  PlaceAssetInSceneCommand,
  PlaceAssetInSceneResult,
  RelocateAssetCommand,
  RelocateAssetResult,
  RenameDatumCommand,
  RenameDatumResult,
  UpdateBodyCommand,
  UpdateBodyResult,
  UpdateDatumPoseCommand,
  UpdateDatumPoseResult,
  UpdateMassPropertiesCommand,
  UpdateMassPropertiesResult,
  SaveProjectCommand,
  SaveProjectResult,
  ScrubCommand,
  SimulationControlCommand,
  SimulationFrame,
  SimulationStateEvent,
  SimulationTrace,
  TimeSample,
  SimulationSettings,
  CompilationDiagnostic,
  SolverSettings,
  ContactSettings,
  UpdateActuatorCommand,
  UpdateActuatorResult,
  UpdateJointCommand,
  UpdateJointResult,
  UpdateLoadCommand,
  UpdateLoadResult,
} from './generated/protocol/transport_pb.js';
export {
  ChannelDataType,
  CompilationDiagnosticSchema,
  ContactSettingsSchema,
  DiagnosticSeverity,
  EngineStatus_State,
  FaceSurfaceClass,
  ImportMode,
  IntegratorType,
  SimStateEnum,
  SimulationAction,
  SolverSettingsSchema,
  SolverType,
} from './generated/protocol/transport_pb.js';
// Binary transport helpers
export {
  createAttachGeometryCommand,
  createCreateActuatorCommand,
  createCreateBodyCommand,
  createCompileMechanismCommand,
  createCreateDatumCommand,
  createCreateDatumFromFaceCommand,
  createCreateJointCommand,
  createCreateLoadCommand,
  createDeleteActuatorCommand,
  createDeleteBodyCommand,
  createDeleteDatumCommand,
  createDeleteJointCommand,
  createDeleteLoadCommand,
  createDetachGeometryCommand,
  createHandshakeCommand,
  createCreatePrimitiveBodyCommand,
  createImportAssetCommand,
  createPlaceAssetInSceneCommand,
  createLoadProjectCommand,
  createNewProjectCommand,
  createPingCommand,
  createRelocateAssetCommand,
  createRenameDatumCommand,
  createUpdateDatumPoseCommand,
  createUpdateMassPropertiesCommand,
  createSaveProjectCommand,
  createScrubCommand,
  createSimulationControlCommand,
  createUpdateActuatorCommand,
  createUpdateBodyCommand,
  createUpdateJointCommand,
  createUpdateLoadCommand,
  engineStateToString,
  eventToDebugJson,
  mapJointType,
  mapMotionType,
  parseEvent,
  toProtoJointType,
  toProtoMotionType,
  type ImportModeType,
  type MotionTypeId,
  type PrimitiveParamsInput,
  type PrimitiveShapeType,
  type SimulationSettingsInput,
  type SolverSettingsInput,
  type ContactSettingsInput,
} from './transport.js';
export {
  createHandshake,
  isCompatible,
  PROTOCOL_NAME,
  PROTOCOL_VERSION,
  type ProtocolHandshake,
} from './version.js';
